Dans le fichier .config régler les parametres de la bdd 
le fichier base model permet d'executer un INSERT INTO, FETCH ALL, UPDADATE et DELETE de maniere général sur toute les tables créer dans le dossier model
On peut également trier sur un id
Lors de la création d'une classe penser a bien mettre les guetteur et setter  de la classe associer a la table (meme nom que les  colones)
Un autoLoader est en place, dans le dossier otherClass
on retrouve également un exemple de classe pour un formulaire et pour une redirection 
